### ISSUE TITLE
Query on denmarf

### ISSUE THREAD

**Issue by nsankar** [ricokaloklo/denmarf#9]
@ricokaloklo It was interesting to read about denmarf and Thanks for developing this great package. 

I would like to ask if this can be used for effective sub-sampling of data from a known distribution of a large dataset. One of the investigations I have been doing at my work is to reduce the size of a clustering model by subsampling the training data with an objective to reduce the size of the data over time and reducing the size of the end model.  Thanks in advance.

**Comment by ricokaloklo** [comment]
Hi @nsankar 

Just to make sure that I understand you correctly, by sub-sampling do you mean generating new samples from a set of "known/given" samples that follow some probability distribution, or do you mean you have a set of samples of dimension N and you want to, effectively, marginalize over some dimension(s) such that the model generates samples of dimension M < N?

Actually `denmarf` can do both cases, but just want to make sure that we are on the same page.

**Comment by nsankar** [comment]
@ricokaloklo Thanks for the response.it is scenario #1 .
